# Generated by Django 3.2 on 2021-05-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=300, verbose_name='Отчество')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
