# Generated by Django 3.2.3 on 2021-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=400, verbose_name='ФИО'),
        ),
    ]
