# Generated by Django 3.2 on 2021-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('prise', models.FloatField(verbose_name='Цена')),
                ('count', models.FloatField(verbose_name='Кол-во')),
                ('data', models.DateTimeField(verbose_name='Дата добавления')),
            ],
        ),
    ]
