# Generated by Django 3.2 on 2021-05-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name': 'Медикамент', 'verbose_name_plural': 'Медикаменты'},
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='data',
        ),
    ]
