# Generated by Django 3.2 on 2021-05-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.category'),
        ),
    ]
