# Generated by Django 3.2 on 2021-05-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_medicines_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.category'),
        ),
    ]
