# Generated by Django 3.2.3 on 2021-05-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_medicines_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='count',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
    ]
