# Generated by Django 3.2 on 2021-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='status',
            field=models.CharField(max_length=256),
        ),
    ]
